### ISSUE TITLE
歌单无法自动或手动更新

### ISSUE THREAD

**Issue by PyroSoar** [metowolf/MetingJS#13]
我在网易云音乐创建了一个歌单，在第一次引用的时候，可以加载歌单信息。
但是该歌单添加新的歌曲的时候，插件引用的歌单并不会更新对应的歌单，好像也无法手动更新，**一直在第一次加载的歌单上**。
歌单的ID号并没有改变，能否设置成自动更新歌单的方式。

[在hexo-tag-aplayer下的issue](https://github.com/MoePlayer/hexo-tag-aplayer/issues/55)

**Comment by metowolf** [comment]
需要等待 24 小时后缓存刷新，或者可以自建 API.

**Comment by PyroSoar** [comment]
嗯嗯，感谢提供api！
