### ISSUE TITLE
请问短期内会取消支持1.x版本嘛？

### ISSUE THREAD

**Issue by angustar** [metowolf/MetingJS#15]
网站出了一些问题，现在看起来是只能支持1.x版本，上2.x版本F12就会报错“Meting.min.js:1 Uncaught TypeError: Cannot read property 'destroy' of undefined”，所以准备暂时先用1.x版本的，请问1.x版本会一直支持下去嘛？有没有取消支持1.x版本的计划…

**Comment by metowolf** [comment]
暂时不会取消支持，另外是否能提供这个问题的复现页面或代码？

**Comment by angustar** [comment]
临时创建了个页面，麻烦大佬帮忙瞧瞧，网址见下条comment。

我插入歌单的方式是在WordPress编辑器中使用文本模式输入：
`<meting-js
	server="netease"
	type="playlist"
	id="60198">
</meting-js>`

不知道添加方式有没有问题……（添加完成后再重新编辑文章这段代码就会消失，所以我一直在怀疑自己添加的方式是不是不对……在1.x版本中使用div标签添加就不会自动消失QAQ）

**Comment by angustar** [comment]
大佬，我新开了一个测试站点，环境完全一致，并且是新建的比较干净，方便大佬调试。网址是http://test.ikaleo.me/index.php/2019/05/22/1/ ，原来的链接就删掉了哈，麻烦不忙的时候帮忙看看是什么情况~

**Comment by metowolf** [comment]
目前没有复现问题，一切正常。能否提供所用的操作系统和浏览器版本

**Comment by angustar** [comment]
Windows 10，64位操作系统；
Chrome浏览器最新版。

刚刚试了一下，这个问题只会在Chrome中出现……
神奇……

![image](https://user-images.githubusercontent.com/34939286/58260279-c2577500-7da8-11e9-9abb-391ae2a2deb2.png)

**Comment by metowolf** [comment]
![image](https://user-images.githubusercontent.com/2666735/58307059-15c0d600-7e30-11e9-9c04-08fd855b890e.png)

以上在 Windows 1905 环境 Chrome 74.0.3729.169 测试，也没有重现问题。
你那边访问 https://i-meto.com/about/ 是否会报错。
