### ISSUE TITLE
解析不了网易云音乐

### ISSUE THREAD

**Issue by kainy** [metowolf/MetingJS#16]
https://api.i-meto.com/meting/api?server=netease&type=playlist&id=21470777，访问后302到首页 了。。

**Comment by metowolf** [comment]
目前屏蔽了直接访问的方式，经过测试 API 运行正常。

**Comment by kainy** [comment]
请问是通过请求的referrer来判断直接访问么。

**Comment by metowolf** [comment]
是的

**Comment by kainy** [comment]
哦哦，那我就明白了，感谢及时回复。
