### ISSUE TITLE
您好，qq音乐好像被腾讯墙了

### ISSUE THREAD

**Issue by buqiyuan** [metowolf/MetingJS#17]
谷歌浏览器控制台出现如下请求错误：
```
GET https://ws.stream.qqmusic.qq.com/M800004gQb5F3tsz7n.mp3?guid=410002021&vkey=DE797989D560CA3C699A1C0A557676DC26C903D87185F078C471FE7E99A63BEDBADAF42F1F74F7410CA6E41827343D2CCD1888BF19268547&uin=0&fromtag=66 net::ERR_CERT_COMMON_NAME_INVALID
```
播放器提示：An audio error has occurred, player will skip forward in 2 seconds.
网易云歌单正常播放，就是qq音乐被forbidden

**Comment by metowolf** [comment]
感谢反馈，应该是 QQ 音乐取消了 ws.stream.qqmusic.qq.com 的 SSL，稍后会进行修复

**Comment by buqiyuan** [comment]
衷心感谢无私的作者，可以了！

**Comment by buqiyuan** [comment]
对了！我想请问一下能否动态切换歌单，对于已经创建好的播放器，直接更换auto的歌单地址无效，是要怎么重新创建歌单列表实例呢？
