### ISSUE TITLE
無法正常顯示圖片

### ISSUE THREAD

**Issue by maple3142** [metowolf/MetingJS#2]
![example](https://i.imgur.com/jXNnCqd.png)
專輯圖片顯示不出來
需要把"pic"的url在瀏覽器上做一次GET request才能顯示
[https://codepen.io/anon/pen/gooRxG?editors=1000](https://codepen.io/anon/pen/gooRxG?editors=1000)

**Comment by metowolf** [comment]
我这里没能重现这个问题，建议贴出控制台报错/警告信息

**Comment by maple3142** [comment]
有來自 aplayer 的錯誤
![](https://i.imgur.com/BHGS408.png)

**Comment by fly3949** [comment]
经测试 Firefox 57.0.4 下可以正常加载图片，不过的确是有报错：
`TypeError: t.lrcContents.getElementsByTagName(...)[0] is undefined`
可以说下浏览器版本吗

**Comment by metowolf** [comment]
我在 windows、macOS 平台下的 Chrome、FireFox 均做过测试，均没能复现这个问题。
建议使用其它浏览器或网络环境再测试一下 😀

**Comment by Genteure** [comment]
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36` 
图片显示完全正常

倒是歌词有地方有问题 :new_moon_with_face: 
```
Uncaught TypeError: Cannot read property 'classList' of undefined
    at XMLHttpRequest.l.onreadystatechange (APlayer.js:680)
l.onreadystatechange @ APlayer.js:680
XMLHttpRequest.send (async)
(anonymous) @ VM181:1
value @ APlayer.js:688
(anonymous) @ APlayer.js:259

L680: this.lrcContents.getElementsByTagName('p')[0].classList.add('aplayer-lrc-current');
```

**Comment by maple3142** [comment]
版本是firebase 58.0b14
