### ISSUE TITLE
歌词默认隐藏

### ISSUE THREAD

**Issue by LiuDanK** [metowolf/MetingJS#23]
我该怎样设置才能让歌词默认不显示呢,现在加载完毕之后总会在底部默认显示歌词

**Comment by first19326** [comment]
我之前也纠结这个问题, 不过我找到了一种解决方案. 在APlayer.js中将"aplayer-lrc-hide"样式直接添加在初始化的歌词显示的标签中, 然后歌词按钮的样式"aplayer-icon-lrc-inactivity"同样直接添加到按钮标签中. 不过这么做就需要将APlayer.js下载下来进行修改, 相对不是特别方便, 也没有CDN加速.

**Comment by fate0101** [comment]
// 隐藏歌词
    ap_global.lrc.hide();
    $(".aplayer.aplayer-fixed .aplayer-icon-lrc").addClass("aplayer-icon-lrc-inactivity");

**Comment by 7u** [comment]
hack以下lrc-type，比如：
```
<meting-js
	server="netease"
	type="playlist"
        lrc-type="1"
	id="60198">
</meting-js>
```

**Comment by crowya** [comment]
我在页脚加入一个延时5秒关闭歌词的函数可近似实现隐藏功能，但这样歌词还是会显示一段时间再关闭，并不完美。
我试过用那些脚本加载完后再执行的函数，但是没用，不知道如何解决。我试过的函数包括：
`window.onload=function(){}`
`$(document).ready(function(){})`
`window.addEventListener('load',function(){})`
似乎都没用。

延时隐藏歌词的代码如下：
```
<script>
	setTimeout(function() {
		document.querySelector('meting-js').aplayer.lrc.hide();
		//$(".aplayer.aplayer-fixed .aplayer-icon-lrc").addClass("aplayer-icon-lrc-inactivity");
		//$(".aplayer.aplayer-fixed .aplayer-lrc").addClass("aplayer-lrc-hide");
		document.querySelector('meting-js').aplayer.on('play', function () {
    			document.querySelector('meting-js').aplayer.lrc.show();
		});
		document.querySelector('meting-js').aplayer.on('pause', function () {
    			document.querySelector('meting-js').aplayer.lrc.hide();
		});
	}, 5000);
</script>
```
其中注释掉的内容是隐藏歌词的另一种写法，两者选其一即可。
后半部分是监听事件，按下播放时显示歌词，按下暂停时隐藏歌词。

**Comment by LiuDanK** [comment]
> 我该怎样设置才能让歌词默认不显示呢,现在加载完毕之后总会在底部默认显示歌词

我修改了默认关闭歌词。
修改完之后的 js文件如下：
[APlayer.min.zip](https://github.com/metowolf/MetingJS/files/4479371/APlayer.min.zip)

**Comment by crowya** [comment]
> > 我该怎样设置才能让歌词默认不显示呢,现在加载完毕之后总会在底部默认显示歌词
> 
> 我修改了默认关闭歌词。
> 修改完之后的 js文件如下：
> [APlayer.min.zip](https://github.com/metowolf/MetingJS/files/4479371/APlayer.min.zip)

有没有仍然使用CDN的方法？

**Comment by LiuDanK** [comment]
> > > 我该怎样设置才能让歌词默认不显示呢,现在加载完毕之后总会在底部默认显示歌词
> > 
> > 
> > 我修改了默认关闭歌词。
> > 修改完之后的 js文件如下：
> > [APlayer.min.zip](https://github.com/metowolf/MetingJS/files/4479371/APlayer.min.zip)
> 
> 有没有仍然使用CDN的方法？

你可以尝试 fate0101 commented on 6 Dec 2019  这条评论的方法，或者将文件加入到自己的cdn对象储存中

**Comment by crowya** [comment]
在保留CDN的前提下，我目前用的是这种方法：
```
<script>
function removelrc(){
	//document.querySelector('meting-js').aplayer.lrc.hide();
	$(".aplayer.aplayer-fixed .aplayer-icon-lrc").addClass("aplayer-icon-lrc-inactivity");
	$(".aplayer.aplayer-fixed .aplayer-lrc").addClass("aplayer-lrc-hide");
	document.querySelector('meting-js').aplayer.on('play', function () {
    		document.querySelector('meting-js').aplayer.lrc.show();
	});
	document.querySelector('meting-js').aplayer.on('pause', function () {
    		document.querySelector('meting-js').aplayer.lrc.hide();
	});
}
document.querySelector('meting-js').addEventListener("DOMNodeInserted",removelrc);
setTimeout(function() {
	document.querySelector('meting-js').removeEventListener("DOMNodeInserted",removelrc);
}, 5000);
</script>
```
主要用到`DOMNodeInserted`监听事件。
虽然依然用了延时函数，但一开始歌词就不会显示，比我上一种方法效果好了一点。
主要问题在于这个监听事件如果一直存在的话即使手动打开歌词也会被马上屏蔽，所以需要5秒后移除监听事件。。。

**Comment by kcn3388** [comment]
添加了一个比较优雅的方式，不需要下载源文件
@crowya @LiuDanK 
```js
function removelrc() {
    //检测是否存在歌词按钮
    if (!document.querySelector(".aplayer-icon-lrc"))
        return;
    else
    {
        //触发以后立刻移除监听
        document.removeEventListener("DOMNodeInserted",removelrc);
        //稍作延时保证触发函数时存在按钮
        setTimeout(function() {
            //以触发按钮的方式隐藏歌词，防止在点击显示歌词按钮时需要点击两次才能出现的问题
            document.querySelector(".aplayer-icon-lrc").click();
        }, 1);
        console.log("success");
        return;
    }
}

document.addEventListener('DOMNodeInserted', removelrc)
```

**Comment by AdingApkgg** [comment]
一个比较现代化的方式
@crowya @LiuDanK @kcn3388 @first19326 @fate0101 @7u
```js
// Aplayer默认关闭歌词
function removelrc() {
  // 检测是否存在歌词按钮
  const lrcIcon = document.querySelector(".aplayer-icon-lrc");
  if (!lrcIcon) {
    return;
  }

  // 触发以后立刻移除监听
  observer.disconnect();

  // 稍作延时保证触发函数时存在按钮
  setTimeout(() => {
    // 以触发按钮的方式隐藏歌词，防止在点击显示歌词按钮时需要点击两次才能出现的问题
    lrcIcon.click();
  }, 1);

  console.log("success");
}

const observer = new MutationObserver((mutationsList, observer) => {
  for (let mutation of mutationsList) {
    if (mutation.type === "childList") {
      removelrc();
    }
  }
});

const observerConfig = {
  childList: true, // 观察子节点的变化
  subtree: true, // 观察所有后代节点的变化
};

observer.observe(document, observerConfig); // 开始观察document节点的变化
```

**Comment by linbabi** [comment]
@kcn3388
稍微改了一下
        // 创建一个MutationObserver实例，用于监听DOM的变化
        var observer = new MutationObserver(function (mutations) {
            // 查找页面中class为"aplayer-icon-lrc"的元素
            var lrcButton = document.querySelector(".aplayer-icon-lrc");
            // 如果找到了lrcButton
            if (lrcButton) {
                // 延迟1毫秒执行点击操作
                setTimeout(function () {
                    lrcButton.click();
                }, 1);
                // 打印"success"到控制台
                console.log("success");
                // 断开MutationObserver实例，停止监听DOM的变化
                observer.disconnect();
            }
        });
        // 监听整个文档及其子节点的变化
        observer.observe(document, { childList: true, subtree: true });

**Comment by linbabi** [comment]
@kcn3388 
稍微修改一下
`
        // 创建一个MutationObserver实例，用于监听DOM的变化
        var observer = new MutationObserver(function (mutations) {
            // 查找页面中class为"aplayer-icon-lrc"的元素
            var lrcButton = document.querySelector(".aplayer-icon-lrc");
            // 如果找到了lrcButton
            if (lrcButton) {
                // 延迟1毫秒执行点击操作
                setTimeout(function () {
                    lrcButton.click();
                }, 1);
                // 打印"success"到控制台
                console.log("success");
                // 断开MutationObserver实例，停止监听DOM的变化
                observer.disconnect();
            }
        });
        // 监听整个文档及其子节点的变化
        observer.observe(document, { childList: true, subtree: true });
`

**Comment by linbabi** [comment]
@kcn3388 
稍微改一下
```
        // 创建一个MutationObserver实例，用于监听DOM的变化
        var observer = new MutationObserver(function (mutations) {
            // 查找页面中class为"aplayer-icon-lrc"的元素
            var lrcButton = document.querySelector(".aplayer-icon-lrc");
            // 如果找到了lrcButton
            if (lrcButton) {
                // 延迟1毫秒执行点击操作
                setTimeout(function () {
                    lrcButton.click();
                }, 1);
                // 打印"success"到控制台
                console.log("success");
                // 断开MutationObserver实例，停止监听DOM的变化
                observer.disconnect();
            }
        });
        // 监听整个文档及其子节点的变化
        observer.observe(document, { childList: true, subtree: true });
```

**Comment by WRXinYue** [comment]
我用的方式，顺便避免了歌词加载闪烁情况
~~~ts
function setupLrcIconHidingObserver() {
  const observer = new MutationObserver((mutations) => {
    /** Hidden ap.lrc */
    function removelrc() {
      const lrcElement = document.querySelector('.aplayer-lrc .aplayer-lrc-contents .aplayer-lrc-current') as HTMLElement
      if (lrcElement) {
        lrcElement.style.display = 'none'
        const lrcButton = document.querySelector('.aplayer-icon-lrc') as HTMLElement
        if (lrcElement?.textContent !== 'Loading') {
          lrcButton.click()
          lrcElement.style.display = ''
          observer.disconnect()
        }
      }
    }
    mutations.forEach((_mutation) => {
      removelrc()
    })
  })
  const config = { childList: true, subtree: true }
  observer.observe(document.body, config)
}
~~~

**Comment by YDTRINLEY** [comment]
> ```
> // 隐藏歌词
> ap_global.lrc.hide();
> $(".aplayer.aplayer-fixed .aplayer-icon-lrc").addClass("aplayer-icon-lrc-inactivity");
> ```

谢谢~简洁有用~🤭

**Comment by YDTRINLEY** [comment]
> hack以下lrc-type，比如：
> 
> ```
> <meting-js
> 	server="netease"
> 	type="playlist"
>         lrc-type="1"
> 	id="60198">
> </meting-js>
> ```

谢谢分享~最简洁有用的一个~🤭
