### ISSUE TITLE
Bug! 非常严重! 在不同环境中加载无效！

### ISSUE THREAD

**Issue by Pevernow** [metowolf/MetingJS#30]
在hexo+uikit+jquery在127.0.0.1运行时失败，通过连接监视显示并没有对api的请求
在同环境保存html文件到本地后可以执行，有对api的请求。

**Comment by metowolf** [comment]
F12，观察开发者工具 Console 中是否有报错信息。

**Comment by Pevernow** [comment]
无报错。已自行解决，问题在于引入js时async，建议在readme中提示不要开async.。
建议对metingjs等待页面加载完成后再运行。
建议监视页面改动（可能动态加入<meting-js>标签）
谢谢
