### ISSUE TITLE
请问api是不是无法连接了

### ISSUE THREAD

**Issue by BrandNewJimZhang** [metowolf/MetingJS#33]
![image](https://user-images.githubusercontent.com/47765973/78464716-498eac80-771f-11ea-8324-5f6ae6685b91.png)
zuo'tian'hai'ke昨天还可以，今天就一直这样

**Comment by Macyrate** [comment]
同，昨晚开始出现这个问题，现在已经完全连不上了

**Comment by Macyrate** [comment]
现在已经复活喽

不过这一波还是让我弄了个Plan B😂

**Comment by BrandNewJimZhang** [comment]
> 现在已经复活喽
> 
> 不过这一波还是让我弄了个Plan B😂

Plan B是什么 好奇

**Comment by Macyrate** [comment]
> > 现在已经复活喽
> > 不过这一波还是让我弄了个Plan B😂
> 
> Plan B是什么 好奇

参考了KuiperSirius的做法：

[index.html](https://github.com/KuiperSirius/KuiperSirius.github.io/blob/8be963825d701b3f7f0d10859523de1ea56cd54e/archives/2020/01/index.html)

翻到最后的部分，有：

```js
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.css">
<div id="aplayer"></div>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.js"></script>
<script type="text/javascript" src="/dist/music.js"></script>
<!--
# APlayer 配置信息及CDN资源加载
# https://www.jsdelivr.com/package/npm/aplayer?path=dist
# https://aplayer.js.org/#/zh-Hans/?id=cdn
<link rel="stylesheet" href="/dist/APlayer.min.css">
<script type="text/javascript" src="/dist/APlayer.min.js"></script>
<script type="text/javascript" src="/dist/music.js"></script>
-->
```

这其实就是APlayer的原版使用方法，没用到Meting，而是用自己写的`/dist/music.js`来加载APlayer。因为我不会JS，之前配置这一套东西费了不少劲……现在看了他的源码总算搞清楚APlayer本来的用法了😂

不过他这个操作着实挺复杂的，本质上是把歌单里的歌、封面、歌词全下载下来传到自己的服务器上。

你问Plan B？那就是直接白嫖他的music.js😂放的也是他的歌单，不过也好过没有（

**Comment by metowolf** [comment]
网站被 DDoS，导致中断了近半天，后续考虑提供云函数搭建方案。
