### ISSUE TITLE
部分手机端浏览器无法调用https://api.i-meto.com/meting/api有办法解决吗

### ISSUE THREAD

**Issue by cdefine** [metowolf/MetingJS#35]
手机自带浏览器无法调用api,音乐插件无法显示

![IMG_20200414_231813](https://user-images.githubusercontent.com/24487003/79246958-76278e80-7eac-11ea-8ee4-80579bcecefb.jpg)

**Comment by cdefine** [comment]
问题已解決：更换了api,修改了一下metingjs文件

**Comment by 721806280** [comment]
请问更换了那个api呢？

**Comment by cdefine** [comment]
> 请问更换了那个api呢？

https://api.mlwei.com/music/api/wy/
