### ISSUE TITLE
SSL站点加载歌曲海报时http的url变成了https

### ISSUE THREAD

**Issue by zackzhangCN** [metowolf/MetingJS#38]
站点https://www.zack.net.cn
歌单是QQ音乐的, chrome浏览器, 歌曲能正常播放, 但是歌曲的海报图片加载不出来, 抓了下包发现图片url应该是http的, 但是加载的却是https

**Comment by metowolf** [comment]
可以贴下有问题的歌曲 ID、图片地址。
之前测试过 QQ 音乐的 https://y.gtimg.cn/ 是完整支持 https 的。

**Comment by zackzhangCN** [comment]
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css">
<script src="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/meting@2/dist/Meting.min.js"></script>
<meting-js
           server="tencent"
           fixed="true"
           type="playlist"
           id="3307722054"
           list-folded="true">
</meting-js>

我发现整个歌单的海报图片都加载不出来了, 抓包把图片url换成http是可以加载的

**Comment by zackzhangCN** [comment]
<meting-js
                                    server="tencent"
                                    type="playlist"
                                    id="3307722054"
                                    list-folded="true">
                            </meting-js>

**Comment by metowolf** [comment]
![](https://y.gtimg.cn/music/photo_new/T002R90x90M0000035FWvO0bwXTo.jpg?max_age=2592000)
https://y.gtimg.cn/music/photo_new/T002R90x90M0000035FWvO0bwXTo.jpg?max_age=2592000
这里测试了下是正常的，可否提供下本地 `ping y.gtimg.cn` 的结果，我反馈上去。

**Comment by zackzhangCN** [comment]
能ping通,  我已经解决了,  是我这边的问题, 这边的上层路由把这个`y.gtimg.cn`拦了, 不好意思...
