### ISSUE TITLE
api 解析服务器宕机？

### ISSUE THREAD

**Issue by Dueot** [metowolf/MetingJS#4]
https://api.i-meto.com/meting/api，请求到这个地址的所有请求全部超时。

**Comment by metowolf** [comment]
![image](https://user-images.githubusercontent.com/2666735/43514556-07e4883a-95b3-11e8-9208-43003657e09c.png)

后端节点一切正常，怀疑是您当前地区干扰 https://api.i-meto.com 访问

**Comment by Dueot** [comment]
嗯，手机访问正常，电脑 ”富强“ 之后还是失败，请问如何解决？

**Comment by metowolf** [comment]
经过确认，其他已知用户未出现异常，建议通过网络工具 (mtr, ping, curl) 测试与该域名的联通性。
