### ISSUE TITLE
您好，不知为何有时候网易云歌单会返回以前的数据

### ISSUE THREAD

**Issue by FastChen** [metowolf/MetingJS#42]
是这样的，我新建了一个歌单做存储，放了一首音乐进去测试，没有问题后开始往里面收藏音乐，但是很长时间不能刷新到全部歌曲，等了一段时间后 能刷新全部但是偶尔刷新页面还会回到只有1首歌测试的时候，而且那首歌已经被移除歌单，不知这是什么问题？

**Comment by metowolf** [comment]
为了降低服务器压力，歌单会缓存 24 小时。

**Comment by FastChen** [comment]
了解
