### ISSUE TITLE
能否设置歌词默认不显示

### ISSUE THREAD

**Issue by SerokSSR** [metowolf/MetingJS#45]
能否设置歌词默认不显示

吸底状态下显示歌词，很容易挡住一些内容，可不可以增加选项，设置歌词默认不显示

**Comment by 850552586** [comment]
```js
var player = document.querySelectorAll('meting-js')[0].aplayer;
player.lrc.hide();
```

**Comment by CappuccinoZ** [comment]
;document.querySelector(".aplayer-icon-lrc").click()
放在Meting.min.js的`this.aplayer=new APlayer(a)`和`}}}console.log`中间即可

**Comment by SerokSSR** [comment]
> ;document.querySelector(".aplayer-icon-lrc").click()
> 放在Meting.min.js的`this.aplayer=new APlayer(a)`和`}}}console.log`中间即可

dalao知道1.2版本的应该怎么改嘛

2.0版本的在我的网站上有一些兼容性问题

**Comment by CappuccinoZ** [comment]
上面那行代码放在1.2版本Meting.min.js的`aplayers.push(new APlayer(r))`和`}}var t`中间也可以

**Comment by SerokSSR** [comment]
可以了 多谢大佬 (*^▽^*)
