### ISSUE TITLE
metingjs与hexo-toc插件冲突，中文标题无法跳转

### ISSUE THREAD

**Issue by huweihuang** [metowolf/MetingJS#5]
感谢作者开源metingjs的功能。
问题描述：
我在博客代码里加入metingjs的引用音乐的功能，然后在toc中的目录跳转时，如果遇到中文目录则无法跳转，英文目录正常跳转。如果将metingjs插件功能注销掉，则toc中文目录正常跳转，猜测是和hexo-toc插件的代码冲突。
具体博客代码参考：https://github.com/huweihuang/www.huweihuang.com/blob/master/themes/huweihuang/layout/post.ejs#L38

问题现象参考：https://www.huweihuang.com/article/kubernetes/kubernetes-resource/

文章中英文toc目录可以正常跳转，中文则当页跳转失败，但是复制地址到新业面则会跳转。

**Comment by cxhttt233** [comment]
+1.....

**Comment by cxhttt233** [comment]
https://blog.wangriyu.wang/2018/06-Aplayer.html 不直到和meting有关系吗

**Comment by cxhttt233** [comment]
@metowolf

**Comment by metowolf** [comment]
这个是 APlayer 的锅，MetingJS 只负责 API 不负责渲染。

**Comment by cxhttt233** [comment]
> 这个是 APlayer 的锅，MetingJS 只负责 API 不负责渲染。

好的谢谢大佬
