### ISSUE TITLE
网易云API出问题了

### ISSUE THREAD

**Issue by ayachi-core-001** [metowolf/MetingJS#59]
昨天不能获取音乐url，今天连playlist也加载不出来了，仅限于网易云平台；难不成是cookie封了？

**Comment by lunzhiPenxil** [comment]
我这也出现相同情况了

**Comment by 0wQ** [comment]
自建的 API 没问题

**Comment by ayachi-core-001** [comment]
> 自建的 API 没问题

可不可以分享一下你的API呢，多谢了

**Comment by 0wQ** [comment]
> > 自建的API没问题
> 
> 可不可以分享一下你的API呢，多谢了


不保证服务稳定性，~~说不定啥时候就给关了~~
为保证缓存，URL 中不要加 `&r=:r` 参数
```html
<script>
var meting_api='//api.iwz.me/meting/api.php?server=:server&type=:type&id=:id'
</script>
```

**Comment by ayachi-core-001** [comment]
> > > 自建的API没问题
> > 
> > 
> > 可不可以分享一下你的API呢，多谢了
> 
> 不保证服务稳定性，~说不定啥时候就给关了~
> 为保证缓存，URL 中不要加 `&r=:r` 参数
> 
> ```
> <script>
> var meting_api='//api.iwz.me/meting/api.php?server=:server&type=:type&id=:id'
> </script>
> ```

多谢了，我试试

**Comment by ayachi-core-001** [comment]
如果可以的话，我想学习一下你的API是怎么写的，比如我这个图片获取的地址总是错误的，头疼；能否私聊，thanks；

**Comment by ayachi-core-001** [comment]
自己的API搭建完成了，多谢各位自己可以丰衣足食！

**Comment by sky456757** [comment]
> 自己的API搭建完成了，多谢各位自己可以丰衣足食！

不好意思打擾了，最近也遇到相同的問題，能否請教一下怎麼自建api呢

**Comment by 0wQ** [comment]
> > 自己的API搭建完成了，多谢各位自己可以丰衣足食！
> 
> 不好意思打擾了，最近也遇到相同的問題，能否請教一下怎麼自建api呢

作者之前发过一个Demo，改一下应该是可以用的
https://gist.github.com/metowolf/25af629b10f6bbf4eaf4af26fbc29915

**Comment by sky456757** [comment]
> > > 自己的API搭建完成了，多谢各位自己可以丰衣足食！
> > 
> > 
> > 不好意思打擾了，最近也遇到相同的問題，能否請教一下怎麼自建api呢
> 
> 作者之前发过一个Demo，改一下应该是可以用的
> https://gist.github.com/metowolf/25af629b10f6bbf4eaf4af26fbc29915

不好意思再次打擾了，可以問一下網易雲cookie的部分是怎麼處理的呢，照著demo架起來發現抓不到資料

**Comment by 0wQ** [comment]
> > > > 自己的API搭建完成了，多谢各位自己可以丰衣足食！
> > > 
> > > 
> > > 不好意思打擾了，最近也遇到相同的問題，能否請教一下怎麼自建api呢
> > 
> > 
> > 作者之前发过一个Demo，改一下应该是可以用的
> > https://gist.github.com/metowolf/25af629b10f6bbf4eaf4af26fbc29915
> 
> 不好意思再次打擾了，可以問一下網易雲cookie的部分是怎麼處理的呢，照著demo架起來發現抓不到資料


https://gist.github.com/metowolf/25af629b10f6bbf4eaf4af26fbc29915#file-api-php-L32

```php
$api=new \Metowolf\Meting($server);

switch ($server) {
    case 'netease':
        $api->cookie('-----COOKIE-----');
}

$api->format(true);
```

**Comment by lemonchu** [comment]
> > > > > 自己的API搭建完成了，多谢各位自己可以丰衣足食！
> > > > 
> > > > 
> > > > 不好意思打擾了，最近也遇到相同的問題，能否請教一下怎麼自建api呢
> > > 
> > > 
> > > 作者之前发过一个Demo，改一下应该是可以用的
> > > https://gist.github.com/metowolf/25af629b10f6bbf4eaf4af26fbc29915
> > 
> > 
> > 不好意思再次打擾了，可以問一下網易雲cookie的部分是怎麼處理的呢，照著demo架起來發現抓不到資料
> 
> https://gist.github.com/metowolf/25af629b10f6bbf4eaf4af26fbc29915#file-api-php-L32
> 
> ```
> $api=new \Metowolf\Meting($server);
> 
> switch ($server) {
>     case 'netease':
>         $api->cookie('-----COOKIE-----');
> }
> 
> $api->format(true);
> ```

邮件联系我就行，我和ayachicore其实是一个人
