### ISSUE TITLE
网易云音乐时有时无，有遇到这个问题的么，好气哦

### ISSUE THREAD

**Issue by wangxinzhi0** [metowolf/MetingJS#62]

**Comment by fyxemmmm** [comment]
单个song是可以的。。我也遇到这个问题

**Comment by saltfish233** [comment]
我也是 单个歌曲可以 歌单就不行了

**Comment by view6view** [comment]
我也是遇到这个问题，有解决办法吗

**Comment by anzhiyu-c** [comment]
我也是QWQ

**Comment by view6view** [comment]
> 我也是QWQ

现在好了，你的网站怎么访问不了

**Comment by anzhiyu-c** [comment]
啊，忘记改了QWQ，先在好了

**Comment by anzhiyu-c** [comment]
好像是报了个跨域，但是我单独打开这个请求的api又是可以的，真难受QAQ

**Comment by view6view** [comment]
> 好像是报了个跨域，但是我单独打开这个请求的api又是可以的，真难受QAQ

我都好久没出现过这个问题了，上一次出现是在3个月之前了，目前使用都是正常的

**Comment by anzhiyu-c** [comment]
我怀疑是请求的次数太多了还是怎么，之前好好的，突然就这样了
