### ISSUE TITLE
api跨域，能不能新加一个meting-js的api服务的配置项

### ISSUE THREAD

**Issue by dengheng12** [metowolf/MetingJS#83]

**Comment by geekswg** [comment]
官方API无法访问了
自定义meting_api
```js
<script>
  // 自定义 meting_api
  var meting_api='https://api.injahow.cn/meting/?server=:server&type=:type&id=:id&auth=:auth&r=:r';
</script>
```
作者: 毕少侠
链接: [https://hexo.geekswg.top/posts/3a28.html#%E8%A7%A3%E5%86%B3](https://hexo.geekswg.top/posts/3a28.html#%E8%A7%A3%E5%86%B3)
来源: 毕少侠
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
