### ISSUE TITLE
QQ音乐分享的链接无法解析

### ISSUE THREAD

**Issue by nexmoe** [metowolf/MetingJS#9]
手机复制的分享链接是：http://url.cn/5HRmBUg
目标链接是：https://y.qq.com/n/yqq/song/97773_num.html 这个链接 meting 无法使用 auto 解析
而这首歌的链接是：https://y.qq.com/n/yqq/song/0039MnYb0qxYhV.html 这个链接 meting 可以使用 auto 解析

**Comment by metowolf** [comment]
这个问题比较棘手，主要是 QQ 音乐同时存在 songid 和 songmid，而 songmid 才能被 Meting 解析。
这里用前端没办法解决 😭
